
global.character_properties = [];
global.character_index = 0;

global.character_queue = [];
global.queue_index = 0;

var _base_move_speed = 1.5 * SIZE_FACTOR;
var _standard_iframes = 60;

// Properties for playing as specific characters
global.character_properties[CHARACTER.NORMAL] = {
	color: $577DEF,
	key: "normal",
	jump_spd: -2.5 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 15,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: _base_move_speed,
	run: spr_player_normal_walk,
	idle: spr_player_normal_idle,
	hurt: spr_player_normal_hurt,
	heavy: false,
	landing_sound: snd_land_normal,
	jumping_sound: snd_jump_normal,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: false,
	can_push_blocks: false,
	can_bounce: false,
	base_health: 1,
	backup_sprites: undefined,
	can_float: false,
	has_twin: false,
	description: "Just a normal guy who likes to jump.",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.TALL] = {
	color: $30BE6A,
	key: "tall",
	jump_spd: -3 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 10,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: _base_move_speed,
	walk_cycle: seq_player_tall_walk,
	idle_cycle: seq_player_tall_idle,
	hurt_cycle: seq_player_tall_hurt,
	run: spr_player_tall_walk,
	idle: spr_player_tall_idle,
	hurt: spr_player_tall_hurt,
	heavy: false,
	landing_sound: snd_land_tall,
	jumping_sound: snd_jump_tall,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: false,
	can_push_blocks: true,
	can_bounce: false,
	base_health: 1,
	backup_sprites: undefined,
	can_float: false,
	has_twin: false,
	description: "Can hit platforms with his tall head",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.BIG] = {
	color: $8A4276,
	key: "big",
	jump_spd: -1.5 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 15,
	grav: 0.3 * SIZE_FACTOR,
	move_spd: 1.25 * SIZE_FACTOR,
	walk_cycle: seq_player_big_walk,
	idle_cycle: seq_player_big_idle,
	hurt_cycle: seq_player_big_hurt,
	run: spr_player_big_walk,
	idle: spr_player_big_idle,
	hurt: spr_player_big_hurt,
	heavy: true,
	landing_sound: snd_land_big,
	jumping_sound: snd_jump_big,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: false,
	can_push_blocks: false,
	can_bounce: false,
	base_health: 1,
	backup_sprites: undefined,
	can_float: false,
	has_twin: false,
	description: "Stomp to destroy all ground monsters",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.SMALL] = {
	color: $FF9B63,
	key: "small",
	jump_spd: -2.5 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 15,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: 2 * SIZE_FACTOR,
	walk_cycle: seq_player_small_walk,
	idle_cycle: seq_player_small_idle,
	hurt_cycle: seq_player_small_hurt,
	run: spr_player_small_walk,
	idle: spr_player_small_idle,
	hurt: spr_player_small_hurt,
	heavy: false,
	landing_sound: snd_land_small,
	jumping_sound: snd_jump_small,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: false,
	can_push_blocks: false,
	can_bounce: false,
	base_health: 1,
	backup_sprites: undefined,
	can_float: false,
	has_twin: false,
	description: "Light, fast, great jumper",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.BOUNCE] = {
	color: $BA7BD7,
	key: "bounce", 
	jump_spd: -2.5 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 15,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: _base_move_speed,
	walk_cycle: seq_player_bounce_walk,
	hurt_cycle: seq_player_bounce_hurt,
	run: spr_player_bounce_walk,
	idle: spr_player_bounce_idle,
	hurt: spr_player_bounce_hurt,
	heavy: false,
	landing_sound: snd_land_bounce,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: true,
	can_push_blocks: false,
	can_bounce: true,
	base_health: 1,
	backup_sprites: undefined,
	can_float: false,
	has_twin: false,
	description: "Can destroy blocks below",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.FLOAT] = 	{
	color: $2C1E19,
	key: "float",
	jump_spd: -3 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 10,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: _base_move_speed,
	walk_cycle: seq_player_float_walk,
	hurt_cycle: seq_player_float_hurt,
	run: spr_player_float_feet,
	idle: spr_player_float_head_idle,
	hurt: spr_player_float_head_hurt,
	heavy: false,
	landing_sound: snd_land_float,
	jumping_sound: snd_jump_float,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: false,
	can_push_blocks: false,
	can_bounce: false,
	base_health: 1,
	backup_sprites: undefined,
	can_float: true,
	has_twin: false,
	description: "Can float upward to reach higher coins",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.SPIKEY] = {
	color: $75CDFF,
	key: "spikey",
	jump_spd: -3 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 10,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: _base_move_speed,
	walk_cycle: seq_player_spikey_walk,
	idle_cycle: seq_player_spikey_idle,
	hurt_cycle: seq_player_spikey_hurt,
	run: spr_player_spikey_idle,
	idle: spr_player_spikey_idle,
	hurt: spr_player_spikey_hurt,
	heavy: false,
	landing_sound: snd_land_spikey,
	jumping_sound: snd_jump_spikey,
	can_destroy_blocks_above: true,
	can_destroy_blocks_below: false,
	can_push_blocks: false,
	can_bounce: false,
	base_health: 1,
	backup_sprites: undefined,
	can_float: false,
	has_twin: false,
	description: "Can destroy blocks above",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.TWIN] = {
	color: $3232AC,
	key: "twin",
	jump_spd: -2.5 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 15,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: 2 * SIZE_FACTOR,
	walk_cycle: seq_player_twin_walk,
	idle_cycle: seq_player_twin_walk,
	hurt_cycle: seq_player_twin_hurt,
	run: spr_player_twins_walk,
	idle: spr_player_twins_idle,
	hurt: spr_player_twins_hurt,
	heavy: false,
	landing_sound: snd_land_twin_on_twin,
	jumping_sound: snd_jump_twin,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: false,
	can_push_blocks: false,
	can_bounce: false,
	base_health: 2,
	backup_sprites: {
		run: spr_player_twins_red_walk,
		idle: spr_player_twins_red_idle,
		hurt: spr_player_twins_red_hurt,
	},
	has_twin: true,
	can_float: false,
	description: "Mirror each other's movements",
	on_hit_iframes: _standard_iframes,
};

global.character_properties[CHARACTER.TWIN_BLUE] = {
	color: $3232AC,
	key: "twin-blue",
	jump_spd: -2.5 * SIZE_FACTOR,
	jump_max: 1,
	jump_hold_frames: 15,
	grav: 0.25 * SIZE_FACTOR,
	move_spd: 2 * SIZE_FACTOR,
	walk_cycle: seq_player_twin_walk_blue,
	idle_cycle: seq_player_twin_walk_blue,
	hurt_cycle: seq_player_twin_hurt_blue,
	run: spr_player_twins_walk,
	idle: spr_player_twins_idle,
	hurt: spr_player_twins_hurt,
	heavy: false,
	landing_sound: snd_land_twin_on_twin,
	jumping_sound: snd_jump_twin,
	can_destroy_blocks_above: false,
	can_destroy_blocks_below: false,
	can_push_blocks: false,
	can_bounce: false,
	base_health: 2,
	backup_sprites: {
		run: spr_player_twins_red_walk,
		idle: spr_player_twins_red_idle,
		hurt: spr_player_twins_red_hurt,
	},
	has_twin: false,
	can_float: false,
	description: "Mirror each other's movements",
	on_hit_iframes: _standard_iframes,
};